Add interpolation and velocity control for 3 grippers
AcutronicRobotics/robotiq_modular_gripper pull request #12
Opened 2019-05-30 11:22 UTC by nzlz

Note that I had to add a `<id>` tag to urdf since we need to identify them in the plugin.

Adding static gripping capabilities is WIP on top of this in the `rework-with-interp-grip` branch.

2019-05-30 11:23 UTC, nzlz commented
Also I have to mention that same as before, hande range goes from 0 to 0.025. Is this happening also in the real gripper? If its different, we should replicate it.

2019-05-30 11:34 UTC, YueErro commented
I will take care of the <id> tag.
Unfortunately, on real driver is not the same i believe.
This measurements are fine, taken from the real robot.

2019-05-30 11:44 UTC, nzlz commented
We should use same values as in real. We just need to know the max opening value for linear goal in hande.

2019-06-03 07:11 UTC, YueErro requested changes

2019-06-03 07:11 UTC, YueErro commented on robotiq_gripper_gazebo_plugins/include/robotiq_gripper_gazebo_plugins/RobotiqGripperPlugin.h
> +      const double MaxVelocity_s50 = 150;
Can we take these values from the urdf?

2019-06-03 07:14 UTC, rkojcev commented on robotiq_gripper_gazebo_plugins/include/robotiq_gripper_gazebo_plugins/RobotiqGripperPlugin.h
> +      const double MaxVelocity_s50 = 150;
that would be ideal instead of hardcoding them here.

2019-06-03 07:25 UTC, nzlz commented
I guess add min, max, and radius to the plugin part of the urdf?

2019-06-03 07:29 UTC, rkojcev commented
That is also an option @nzlz

2019-06-03 07:34 UTC, YueErro commented
They are already there ([limit](https://github.com/AcutronicRobotics/robotiq_modular_gripper/blob/master/robotiq_hande_gripper_description/urdf/robotiq_hande.urdf.xacro#L98)).

2019-06-03 07:44 UTC, rkojcev commented
Lets use these values then @nzlz and @YueErro

2019-06-03 08:05 UTC, nzlz commented
We dont have lower velocity limits there. Also, which are the units? I guess revolute rad/s and prismatic m/s?

Also, can we trust these max values? Right now the s85 has a higher max limit in the urdf than the s140, that is incorrect. In the plugin I did the calculation using the radius of the angular movement, which is not a precise value. (measured in gazebo +-)

2019-06-03 08:13 UTC, YueErro commented
The units and limits are [these](https://github.com/erlerobot/management/issues/1870#issuecomment-487074368) ones, taken from the real grippers, not from the real driver.

2019-06-03 08:15 UTC, YueErro commented
Instead of taking them from the limit tag we can add each min-max tags in the plugin, same as [PID values](https://github.com/AcutronicRobotics/robotiq_modular_gripper/blob/master/robotiq_hande_gripper_description/urdf/robotiq_hande.urdf.xacro#L104-L106).

2019-06-03 08:17 UTC, nzlz commented
Yes i think adding to the plugin part in urdf is the best option.

2019-06-04 09:37 UTC, nzlz commented
Forgot to mention that I removed the `id` tag since we decided to use the following:

```xml
        <min_velocity>X</min_velocity>
        <max_velocity>X</max_velocity>
        <radius>X</radius> <!--Only for revolute joints-->
```

2019-06-10 09:13 UTC, ahcorde commented
we need to resolve some issues to be able to merge with master @yue or @nzlz can you take care?

2019-06-10 09:28 UTC, nzlz commented
Pushed merge. @YueErro can you review? 

Ill test everything again to make sure its working fine.

2019-06-10 10:33 UTC, nzlz commented
Merge master working. Don't merge. Fix WIP

2019-06-10 10:34 UTC, YueErro commented
The plugin is duplicated.

2019-06-10 11:23 UTC, nzlz commented
## PR tests

- [x] S140
- [x] S85
- [x] S50 (hande)

---
Example for S140 (revolute, so using angular position, linear is not used)
terminal1
```bash
ros2 launch robotiq_gazebo robotiq_140.launch.py
```
Terminal2

```bash
ros2 service call /hrim_actuator_gripper_000000000004/fingercontrol hrim_actuator_gripper_srvs/ControlFinger "{goal_linearposition: 0.0, goal_angularposition: 0.0, goal_velocity: 100.0}"
```

2019-06-10 11:29 UTC, YueErro approved these changes

2019-06-10 11:29 UTC, ahcorde approved these changes

2019-06-10 11:29 UTC, merged